POST http://localhost:3001/sessions/2
Content-Type: application/json

{
    "lifts": {
        "deadlift": {"mass": [155, 160, 167.5, 160], "reps": [1,1,1,1], "variation": ["Conventional", "Mixed"]},
        "bench": {"mass": [80, 85, 90, 95, 90, 90], "reps": [5,3,1,1,1,1], "variation": ["Wide Grip", "Flat"]},
        "squat": {"mass": [130, 137.5, 142.5, 137.5, 130, 120], "reps": [3, 1, 1, 1, 3, 5], "variation": ["High Bar"]}
    },
    "date": "2022-08-20T04:51:31.790Z"
}

###

GET http://localhost:3001/sessions/2

###

POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "secondUser",
    "password": "second"
}


###

DELETE http://localhost:3001/sessions/24

###

PUT http://localhost:3001/sessions/2/26
Content-Type: application/json

{
    "lifts": {
        "deadlift": {"mass": [155, 160, 167.5, 160], "reps": [1,1,1,1], "variation": ["Conventional", "Mixed"]},
        "squat": {"mass": [130, 137.5, 142.5, 137.5, 130, 120], "reps": [3, 1, 1, 1, 3, 5], "variation": ["High Bar"]}                
    },
    "newLifts": {},
    "lostLifts": [],
    "date": "2022-07-19T04:51:31.790Z"
}

###

PUT http://localhost:3001/change/1
Content-Type: application/json

{
    "password": "howaboutnow"
}
